clients/js/package.json, clients/js/src/generated/instructions/createAssociatedToken.ts, clients/js/src/generated/instructions/createAssociatedTokenIdempotent.ts, clients/js/src/generated/instructions/recoverNestedAssociatedToken.ts, clients/js/src/generated/programs/associatedToken.ts, clients/js/test/createAssociatedToken.test.ts, clients/js/test/createAssociatedTokenIdempotent.test.ts, program/idl.json
=> Add Instruction discriminators to Associated Token Program

clients/js/src/generated/instructions/amountToUiAmount.ts, clients/js/src/generated/instructions/approve.ts, clients/js/src/generated/instructions/approveChecked.ts, clients/js/src/generated/instructions/burn.ts, clients/js/src/generated/instructions/burnChecked.ts, clients/js/src/generated/instructions/closeAccount.ts, clients/js/src/generated/instructions/createAssociatedToken.ts, clients/js/src/generated/instructions/createAssociatedTokenIdempotent.ts, clients/js/src/generated/instructions/freezeAccount.ts, clients/js/src/generated/instructions/getAccountDataSize.ts, clients/js/src/generated/instructions/initializeAccount.ts, clients/js/src/generated/instructions/initializeAccount2.ts, clients/js/src/generated/instructions/initializeAccount3.ts, clients/js/src/generated/instructions/initializeImmutableOwner.ts, clients/js/src/generated/instructions/initializeMint.ts, clients/js/src/generated/instructions/initializeMint2.ts, clients/js/src/generated/instructions/initializeMultisig.ts, clients/js/src/generated/instructions/initializeMultisig2.ts, clients/js/src/generated/instructions/mintTo.ts, clients/js/src/generated/instructions/mintToChecked.ts, clients/js/src/generated/instructions/recoverNestedAssociatedToken.ts, clients/js/src/generated/instructions/revoke.ts, clients/js/src/generated/instructions/setAuthority.ts, clients/js/src/generated/instructions/syncNative.ts, clients/js/src/generated/instructions/thawAccount.ts, clients/js/src/generated/instructions/transfer.ts, clients/js/src/generated/instructions/transferChecked.ts, clients/js/src/generated/instructions/uiAmountToAmount.ts, package.json, pnpm-lock.yaml
Bumping token client to pick up https://github.com/kinobi-so/kinobi/pull/224 
As renderers-js bumps from 0.21.2 to 0.21.9 there are some other changes in the generated js client here too
=> Bump kinobi versions, with renderers-js to 0.21.9

program/Cargo.toml, program/README.md, program/src/entrypoint.rs, program/src/error.rs, program/src/instruction.rs, program/src/lib.rs, program/src/native_mint.rs, program/src/processor.rs, program/src/state.rs, program/tests/assert_instruction_count.rs
It's time to move over the SPL Token program implementation to its specific repo, but it hasn't been done.
Following the PR for the token-metadata program at https://github.com/solana-program/token-metadata/pull/1, I ran:
```
git remote add spl https://github.com/solana-labs/solana-program-library.git
git fetch spl master:fromspl
git switch fromspl
git remote rm spl
python3 ../../git-filter-repo \
--path token/program \
--path-rename token/program:program \
--force
git remote add origin git@github.com:joncinque/token.git
git fetch origin main
git switch main
git switch fromspl
git rebase main
```
NOTE: CI is not included yet
=> program: Port from SPL

.github/workflows/dependabot-auto-merge.yml
Dependabot is not configured to merge PRs automatically on the repo.
Add dependabot config.
=> CI: Add dependabot auto-merge

.github/workflows/main.yml, program/tests/processor.rs
PR #17 moved processors tests to the `tests` folder but instructions are executed directly against the program `Processor`.
Reimplement both `do_process_instruction` and `do_process_instruction_dups` to use `mollusk` to execute instructions.
While the intention was not to introduce any changes to existing tests, there were a couple of changes required:
- Few tests that were using the `Processor` directly were updated to use `do_process_instruction_dups`
- assert after the account is closed tests if the data is empty on`test_close_account`
=> tests: Use mollusk on process instruction

Cargo.lock, program/Cargo.toml, program/tests/assert_instruction_count.rs, program/tests/close_account.rs, program/tests/processor.rs, program/tests/setup.rs
While PR #18 updates the processor tests to use mollusk, the validation checks are done "outside" mollusk.
This PR adds `Check`s to process instruction. It leaves the existing validation checks as well to guarantee the same behaviour.
=> tests: Add process instruction checks

p-token/src/processor/get_account_data_size.rs, p-token/src/processor/revoke.rs, p-token/src/processor/set_authority.rs, p-token/src/processor/shared/approve.rs, p-token/src/processor/shared/initialize_account.rs, p-token/src/processor/shared/transfer.rs
This PR fixes a typo on the processor implementation of `p-token` ("remaning" -> "remaining").
=> p-token: Fix typo

Cargo.lock, interface/README.md, p-token/tests/amount_to_ui_amount.rs, p-token/tests/approve.rs, p-token/tests/approve_checked.rs, p-token/tests/burn.rs, p-token/tests/burn_checked.rs, p-token/tests/close_account.rs, p-token/tests/freeze_account.rs, p-token/tests/initialize_account.rs, p-token/tests/initialize_account2.rs, p-token/tests/initialize_account3.rs, p-token/tests/initialize_mint.rs, p-token/tests/initialize_mint2.rs, p-token/tests/initialize_multisig.rs, p-token/tests/initialize_multisig2.rs, p-token/tests/mint_to.rs, p-token/tests/mint_to_checked.rs, p-token/tests/revoke.rs, p-token/tests/set_authority.rs, p-token/tests/thaw_account.rs, p-token/tests/transfer.rs, p-token/tests/transfer_checked.rs, p-token/tests/ui_amount_to_amount.rs, package.json
Currently it is not possible to build and test `p-token` program using `pnpm` scripts.
Add `p-token:build` and `p-token:test` to `package.json` to build and test the program.
Starting from a fresh clone:
```
pnpm install
```
to install `pnpm` dependencies. Then we can use:
```
pnpm p-token:build
```
to build `p-token` binary – it will be located at `./target/deploy/pinocchio_token_program.so`. You can also use:
```
pnpm p-token:test
```
to run `p-token` tests.
=> p-token: Add scripts

.github/workflows/main.yml, package.json, program/tests/processor.rs, scripts/rust/fixtures.mjs
This PR adds a script to run `spl-token` fixtures against the `p-token` program (342 fixtures in total).
=> p-token: Add `spl-token` test fixtures

Cargo.lock, interface/Cargo.toml, interface/src/error.rs, p-token/Cargo.toml, p-token/src/entrypoint.rs, p-token/src/processor/mod.rs, package.json
Currently, `p-token` does not log an error message – this is different than the current SPL Token implementation.
Add error logging.
The PR also updates pinocchio dependencies to use the `ToStr` trait.
=> p-token: Add error logging

Cargo.lock, interface/Cargo.toml, interface/src/lib.rs, p-token/src/entrypoint.rs
Currently the interface crate is no_std "friendly", but it is missing the no_std attribute. This brings the `std` during the link stage and prevents the program from using the `nostd_panic_handler`.
Add the no_std attribute to the interface crate, update the dependencies so all of them are compatible with no_std and use the `nostd_panic_handler` on p-token.
=> interface: Add `no_std` attribute

.github/workflows/publish-rust.yml
There's an extra space in the manifest path, causing the publish job to fail.
Remove it
=> CI: Remove space in package path

p-token/src/entrypoint.rs, p-token/src/processor/amount_to_ui_amount.rs, p-token/src/processor/initialize_multisig2.rs, p-token/src/processor/ui_amount_to_amount.rs, p-token/src/processor/withdraw_excess_lamports.rs
`p-token` processor is divided into "fast" and "normal", where the "fast" is responsible for a small subset of instructions to reduce the number of comparisons to determine which instruction to execute. Instructions that are not placed on the "fast" tend to have CU overhead, therefore popular instructions such as `transfer_checked`, `burn` and `burn_checked` should be placed on the "fast" path.
Move `transfer_checked`, `burn` and `burn_checked` to the "fast" processor. This PR also removes `inline` attributes of some processors where there are no gains in CUs for doing that.
=> p-token: Tweaks to processors

p-token/src/processor/withdraw_excess_lamports.rs, p-token/tests/withdraw_excess_lamports.rs
Currently there is no mechanism to withdraw excess lamports from mint accounts with no authority. In such scenarios, #48 proposes to allow the mint keypair to withdraw the excess lamports.
This PR updates the `withdraw_excess_lamports` instruction to allow withdraw when the authority is the same as the mint, it is a signer and the mint does not have an authority.
=> p-token: Allow withdraw excess lamports from mint without authority

interface/src/state/account.rs, interface/src/state/mint.rs, interface/src/state/mod.rs, interface/src/state/multisig.rs
The `Transmutable` trait has memory safety implications in its implementation, but it is not marked as `unsafe`. This is problematic since undefined behaviour can result from an incorrect implementation.
Add `unsafe` to `Transmutable` trait to make it explicit that the trait has to be carefully implemented.
cc: @d0nutptr
=> p-token: Add unsafe to transmutable trait

p-token/src/processor/close_account.rs, p-token/src/processor/mod.rs, p-token/src/processor/revoke.rs, p-token/src/processor/set_authority.rs, p-token/src/processor/shared/approve.rs, p-token/src/processor/shared/burn.rs, p-token/src/processor/shared/mint_to.rs, p-token/src/processor/shared/toggle_account_state.rs, p-token/src/processor/shared/transfer.rs, p-token/src/processor/withdraw_excess_lamports.rs
The `validate_owner` helper function has specific safety requirements to avoid undefine behaviour: the `owner_account_info` cannot be mutably borrowed. At the same time, the function is not qualified as `unsafe`.
Add the `unsafe` qualifier to the function and update every callsite.
cc: @d0nutptr
=> p-token: Add `unsafe` qualifier to validate owner

.github/workflows/main.yml
There are program tests in the `p-token` implementation that are not being used in CI.
Add a job to run `p-token` program tests to the CI.
=> ci: Add p-token test to workflow

Cargo.lock, Cargo.toml, interface/Cargo.toml, p-token/Cargo.toml
There are newer pinocchio crates published.
Update the pinocchio dependencies.
=> p-token: Use latest pinocchio crates

Cargo.lock, Cargo.toml, interface/Cargo.toml, interface/src/error.rs, program/Cargo.toml
The interface crate is still on the v2 sdk crates, but the v3 crates are ready.
Bump the sdk crates to v3 and decouple the program from the repo version of the interface crate. The only change is the `to_str` signature on the error.
While doing this, I noticed that the interface crate wasn't actually part of the workspace, so I added it in.
=> deps: Bump sdk to v3, decouple from token program

Cargo.lock, Cargo.toml, p-token/Cargo.toml, p-token/src/processor/batch.rs, p-token/tests/batch.rs, program/Cargo.toml
Few Instructions require specific account ownership checks when executed in a batch since ownership is only enforced by the runtime at the end of the batch processing.
Add specific ownership checks for instructions when they are executed in batch.
=> p-token: Add explicitly ownership checks in `batch`

p-interface/src/lib.rs, p-interface/src/state/account.rs, p-token/src/processor/mod.rs, p-token/src/processor/shared/transfer.rs
It is possible to reduce CU consumption in the transfer instruction by using hints to the compiler, which allow it to optimize the code for the likely (hot) path.
This PR adds compiler hints to the transfer instruction.
=> branch hints

p-token/src/processor/shared/transfer.rs
Currently, both amount and lamports are validated during a transfer involving native accounts. Since amount is already validated, it is not strictly necessary to validate lamports as well.
Use unchecked operations when manipulating lamport values, which reduces CU consumption.
=> reuse amount validations

p-token/tests/initialize_immutable_owner.rs, p-token/tests/sync_native.rs
Both `initialize_mutable_owner` and `sync_native` are relatively popular instructions, but currently there are no tests for them in p-token. This prevents getting CU consumption values when benchmarking changes.
Add tests for them so CUs are reported.
=> p-token: Add more tests

p-token/src/processor/close_account.rs, p-token/src/processor/shared/burn.rs, p-token/src/processor/withdraw_excess_lamports.rs
Following #82, there are a few more places where math operations can be simplified since it is guaranteed that values will be within the valid limit.
Simplify math operation, which leads to reduction in CU.
| instruction | Before | After |
|------------|-------|-------|
| burn           | 123     |  122    |
|close_account | 123  |  116 |
| burn_checked | 126 | 125 |
withdraw_excess_lamports | 292 | 284 |
=> p-token: Simplify math operations

p-token/src/entrypoint.rs
Currently `p-token` uses the "generic" entrypoint. There is an opportunity to give priority to most used instruction to further save CUs. Looking at token instructions from a period of one month, the most used instructions are:
| Instruction                                | Usage (%) |
| ----------------------------- | ----------- |
| `transfer_checked`                 |  `36.33%` |
| `transfer`                                 | `13.22%`   |
| `close_account`                      | `12.23%`   |
| `initialize_account3`               | `9.98%`    |
| `initialize_immutable_owner` | `9.78%`    |
| `sync_native`                           | `4.53%`    |
| `initialize_account`                  | `2.58%`    |
Other instructions account for less than `1%` each.
This PR adds a custom entrypoint to …
=> p-token: Add custom entrypoint
